### ISSUE TITLE
Unable to set Content-Type header

### ISSUE THREAD

**Issue by morimekta** [morimekta/providence#6]
In the pvd RPC tool.

pvdrpc -H "Content-Type: application/x-thrift" results in an exception:

Exception in thread "main" java.lang.IllegalArgumentException: Can not set java.util.List field com.google.api.client.http.HttpHeaders.contentType to java.lang.String
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.google.api.client.util.FieldInfo.setFieldValue(FieldInfo.java:245)
	at com.google.api.client.util.FieldInfo.setValue(FieldInfo.java:206)
	at com.google.api.client.util.GenericData.set(GenericData.java:125)
	at com.google.api.client.http.HttpHeaders.set(HttpHeaders.java:175)
	at net.morimekta.providence.rpc.handler.SetHeadersInitializer.initialize(SetHeadersInitializer.java:30)
	at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:93)
	at com.google.api.client.http.HttpRequestFactory.buildPostRequest(HttpRequestFactory.java:133)
	at net.morimekta.providence.client.HttpClientHandler.handleCall(HttpClientHandler.java:51)
	at net.morimekta.providence.rpc.RPC.run(RPC.java:85)
	at net.morimekta.providence.rpc.RPC.main(RPC.java:144)

**Comment by morimekta** [comment]
Fixed.
