### ISSUE TITLE
Cannot extend service from included file

### ISSUE THREAD

**Issue by zhaakhi** [morimekta/providence#81]
On master, given e.g. these changes to the test cases:

```diff --git a/providence-testing/src/test/providence/service.thrift b/providence-testing/src/test/providence/service.thrift
index 8d9fd41e..7578f6c8 100644
--- a/providence-testing/src/test/providence/service.thrift
+++ b/providence-testing/src/test/providence/service.thrift
@@ -44,3 +44,9 @@ service TestService2  {
     set<string> returnaset();
     list<i32> returnalist();
 }
+
+service TestService3 extends service2.BaseTestService {
+}
+
+service TestService4 extends service2.BaseTestService2 {
+}
diff --git a/providence-testing/src/test/providence/service2.thrift b/providence-testing/src/test/providence/service2.thrift
index ead5837c..89ac90e9 100644
--- a/providence-testing/src/test/providence/service2.thrift
+++ b/providence-testing/src/test/providence/service2.thrift
@@ -4,3 +4,11 @@ struct Request {
     1: string text;
     2: bool valid;
 }
+
+service BaseTestService {
+    i32 inBaseService();
+}
+
+service BaseTestService2 {
+    i32 inBaseService();
+}
```

Compilation will fail with the following error
```
[ERROR] Failed to execute goal net.morimekta.providence:providence-maven-plugin:0.5.2-SNAPSHOT:testCompile (generate-sources-for-test) on project providence-testing: Execution generate-sources-for-test of goal net.morimekta.providence:providence-maven-plugin:0.5.2-SNAPSHOT:testCompile failed: No such program "service2" known for service "service2.BaseTestService2" -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.morimekta.providence:providence-maven-plugin:0.5.2-SNAPSHOT:testCompile (generate-sources-for-test) on project providence-testing: Execution generate-sources-for-test of goal net.morimekta.providence:providence-maven-plugin:0.5.2-SNAPSHOT:testCompile failed: No such program "service2" known for service "service2.BaseTestService2"
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-sources-for-test of goal net.morimekta.providence:providence-maven-plugin:0.5.2-SNAPSHOT:testCompile failed: No such program "service2" known for service "service2.BaseTestService2"
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalArgumentException: No such program "service2" known for service "service2.BaseTestService2"
	at net.morimekta.providence.reflect.util.RecursiveTypeRegistry.getService(RecursiveTypeRegistry.java:112)
	at net.morimekta.providence.util.BaseTypeRegistry.lambda$getServiceProvider$1(BaseTypeRegistry.java:126)
	at net.morimekta.providence.descriptor.PService.getExtendsService(PService.java:99)
	at net.morimekta.providence.reflect.contained.CService.getExtendsService(CService.java:71)
	at net.morimekta.providence.reflect.contained.CService.getExtendsService(CService.java:35)
	at net.morimekta.providence.util.BaseTypeRegistry.registerRecursively(BaseTypeRegistry.java:132)
	at net.morimekta.providence.reflect.util.ProgramConverter.convert(ProgramConverter.java:252)
	at net.morimekta.providence.reflect.TypeLoader.load(TypeLoader.java:175)
	at net.morimekta.providence.maven.plugin.BaseGenerateSourcesMojo.executeInternal(BaseGenerateSourcesMojo.java:295)
	at net.morimekta.providence.maven.plugin.GenerateTestSourcesMojo.execute(GenerateTestSourcesMojo.java:86)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

This appears to be a regression.
There may be three errors here:
1. not giving file name and line number for the error.
2. not resolving service2.BaseTestService2
3. resolving service2.BaseTestService to the local BaseTestService definition

**Comment by morimekta** [comment]
Fixed in master branch.
