### ISSUE TITLE
Bad exception when failing to get enum map key in config.

### ISSUE THREAD

**Issue by morimekta** [morimekta/providence#97]
```
Caused by: java.lang.NullPointerException: null key in entry: null=http://fsc.test.zobj.net
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32)
	at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49)
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:122)
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:198)
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:213)
	at com.google.common.collect.ImmutableMap$Builder.putAll(ImmutableMap.java:241)
	at com.google.common.collect.ImmutableMap$Builder.putAll(ImmutableMap.java:224)
	at net.morimekta.providence.descriptor.PMap$DefaultBuilder.putAll(PMap.java:137)
	at net.morimekta.providence.config.impl.ProvidenceConfigParser.parseMapValue(ProvidenceConfigParser.java:726)
	at net.morimekta.providence.config.impl.ProvidenceConfigParser.parseMessage(ProvidenceConfigParser.java:673)
	at net.morimekta.providence.config.impl.ProvidenceConfigParser.parseConfigMessage(ProvidenceConfigParser.java:428)
	at net.morimekta.providence.config.impl.ProvidenceConfigParser.parseConfigRecursively(ProvidenceConfigParser.java:251)
	at net.morimekta.providence.config.impl.ProvidenceConfigParser.checkAndParseInternal(ProvidenceConfigParser.java:144)
	at net.morimekta.providence.config.impl.ProvidenceConfigParser.parseConfigRecursively(ProvidenceConfigParser.java:202)
	at net.morimekta.providence.config.impl.ProvidenceConfigParser.checkAndParseInternal(ProvidenceConfigParser.java:144)
	at net.morimekta.providence.config.impl.ProvidenceConfigParser.parseConfig(ProvidenceConfigParser.java:113)
	at net.morimekta.providence.config.impl.ProvidenceConfigSupplier.loadConfig(ProvidenceConfigSupplier.java:136)
	at net.morimekta.providence.config.impl.ProvidenceConfigSupplier.<init>(ProvidenceConfigSupplier.java:92)
	at net.morimekta.providence.config.ProvidenceConfig.resolveConfig(ProvidenceConfig.java:105)
	at net.morimekta.providence.config.ProvidenceConfig.getConfig(ProvidenceConfig.java:143)
```

**Comment by morimekta** [comment]
This was fixed in 1.3.0
